// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EscapeRoomAPI.Entities;

public partial class EscapeRoomUnityContext : DbContext
{
    public EscapeRoomUnityContext(DbContextOptions<EscapeRoomUnityContext> options)
        : base(options)
    {
    }

    public virtual DbSet<GameSession> GameSessions { get; set; }

    public virtual DbSet<Leaderboard> Leaderboards { get; set; }

    public virtual DbSet<Player> Players { get; set; }

    public virtual DbSet<PlayerGameAnswer> PlayerGameAnswers { get; set; }

    public virtual DbSet<PlayerGameSession> PlayerGameSessions { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<QuestionAnswer> QuestionAnswers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(GetConnectionString());
    }

    private string GetConnectionString()
    {
        IConfiguration config = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json")
            .Build();
        return config.GetConnectionString("DefaultDB");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<GameSession>(entity =>
        {
            entity.HasKey(e => e.SessionId).HasName("PK__GameSess__C9F49290FB8C60D6");

            entity.ToTable("GameSession");

            entity.Property(e => e.Hint).HasMaxLength(100);
            entity.Property(e => e.SessionCode).HasMaxLength(100);
            entity.Property(e => e.SessionName).HasMaxLength(100);
        });

        modelBuilder.Entity<Leaderboard>(entity =>
        {
            entity.HasKey(e => e.LeaderBoardId).HasName("PK__Leaderbo__91D4421493D00BC0");

            entity.ToTable("Leaderboard");

            entity.HasIndex(e => e.PlayerId, "IX_Leaderboard_PlayerId");

            entity.HasIndex(e => e.SessionId, "IX_Leaderboard_SessionId");

            entity.Property(e => e.PlayerId)
                .IsRequired()
                .HasMaxLength(36);

            entity.HasOne(d => d.Player).WithMany(p => p.Leaderboards)
                .HasPrincipalKey(p => p.PlayerId)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Leaderboard_PlayerId");

            entity.HasOne(d => d.Session).WithMany(p => p.Leaderboards)
                .HasForeignKey(d => d.SessionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Leaderboard_SessionId");
        });

        modelBuilder.Entity<Player>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Player__3213E83F4347761C");

            entity.ToTable("Player");

            entity.HasIndex(e => e.PlayerId, "AK_Player_PlayerId").IsUnique();

            entity.HasIndex(e => e.PlayerId, "UQ__Player__4A4E74C9B7D270D4").IsUnique();

            entity.HasIndex(e => e.Username, "UQ__Player__536C85E4DBC68C1A").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PlayerId)
                .IsRequired()
                .HasMaxLength(36)
                .HasDefaultValueSql("(CONVERT([nvarchar](36),newid()))");
            entity.Property(e => e.RegistrationDate).HasColumnType("datetime");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(25);
        });

        modelBuilder.Entity<PlayerGameAnswer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PlayerGa__3213E83F4F401746");

            entity.ToTable("PlayerGameAnswer");

            entity.HasIndex(e => e.PlayerId, "IX_PlayerGameAnswer_PlayerId");

            entity.HasIndex(e => e.QuestionId, "IX_PlayerGameAnswer_QuestionId");

            entity.HasIndex(e => e.SelectAnswerId, "IX_PlayerGameAnswer_SelectAnswerId");

            entity.HasIndex(e => e.SessionId, "IX_PlayerGameAnswer_SessionId");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.PlayerId)
                .IsRequired()
                .HasMaxLength(36);
            entity.Property(e => e.QuestionId)
                .IsRequired()
                .HasMaxLength(36);
            entity.Property(e => e.SelectAnswerId)
                .IsRequired()
                .HasMaxLength(36);

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerGameAnswers)
                .HasPrincipalKey(p => p.PlayerId)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlayerGameAnswer_PlayerId");

            entity.HasOne(d => d.Question).WithMany(p => p.PlayerGameAnswers)
                .HasPrincipalKey(p => p.QuestionId)
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlayerGameAnswer_QuestionId");

            entity.HasOne(d => d.SelectAnswer).WithMany(p => p.PlayerGameAnswers)
                .HasPrincipalKey(p => p.QuestionAnswerId)
                .HasForeignKey(d => d.SelectAnswerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlayerGameAnswer_SelectAnswerId");

            entity.HasOne(d => d.Session).WithMany(p => p.PlayerGameAnswers)
                .HasForeignKey(d => d.SessionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlayerGameAnswer_SessionId");
        });

        modelBuilder.Entity<PlayerGameSession>(entity =>
        {
            entity.HasKey(e => new { e.SessionId, e.PlayerId }).HasName("PK__PlayerGa__5D5075DCDD5F45CC");

            entity.ToTable("PlayerGameSession");

            entity.HasIndex(e => e.PlayerId, "IX_PlayerGameSession_PlayerId");

            entity.Property(e => e.PlayerId).HasMaxLength(36);

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerGameSessions)
                .HasPrincipalKey(p => p.PlayerId)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlayerGameSession_PlayerId");

            entity.HasOne(d => d.Session).WithMany(p => p.PlayerGameSessions)
                .HasForeignKey(d => d.SessionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlayerGameSession_SessionId");
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Question__3213E83F406A6A02");

            entity.ToTable("Question");

            entity.HasIndex(e => e.QuestionId, "AK_Question_QuestionId").IsUnique();

            entity.HasIndex(e => e.QuestionId, "UQ__Question__0DC06FAD6C8FB79C").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.QuestionDesc)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.QuestionId)
                .IsRequired()
                .HasMaxLength(36)
                .HasDefaultValueSql("(CONVERT([nvarchar](36),newid()))");
        });

        modelBuilder.Entity<QuestionAnswer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Question__3213E83F3EFFC6F3");

            entity.ToTable("QuestionAnswer");

            entity.HasIndex(e => e.QuestionAnswerId, "AK_QuestionAnswer_QuestionAnswerId").IsUnique();

            entity.HasIndex(e => e.QuestionId, "IX_QuestionAnswer_QuestionId");

            entity.HasIndex(e => e.QuestionAnswerId, "UQ__Question__86BEDFCE4C0C15DA").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Answer).HasMaxLength(150);
            entity.Property(e => e.QuestionAnswerId)
                .IsRequired()
                .HasMaxLength(36)
                .HasDefaultValueSql("(CONVERT([nvarchar](36),newid()))");
            entity.Property(e => e.QuestionId).HasMaxLength(36);

            entity.HasOne(d => d.Question).WithMany(p => p.QuestionAnswers)
                .HasPrincipalKey(p => p.QuestionId)
                .HasForeignKey(d => d.QuestionId)
                .HasConstraintName("FK_QuestionAnswer_QuestionId");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}