// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EscapeRoomAPI.Entities;

public partial class Leaderboard
{
    public int LeaderBoardId { get; set; }

    public int SessionId { get; set; }

    public string PlayerId { get; set; }

    public int? TotalRightAnswer { get; set; }

    public virtual Player Player { get; set; }

    public virtual GameSession Session { get; set; }
}