// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EscapeRoomAPI.Entities;

public partial class PlayerGameSession
{
    public int SessionId { get; set; }

    public string PlayerId { get; set; }

    public bool? IsHost { get; set; }

    public bool? IsReady { get; set; }

    public virtual Player Player { get; set; } 

    public virtual GameSession Session { get; set; }
}