// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EscapeRoomAPI.Entities;

public partial class Question
{
    public int Id { get; set; }

    public string QuestionId { get; set; }

    public string QuestionDesc { get; set; }

    public string Image { get; set; }

    public int KeyDigit { get; set; }

    public bool IsHard { get; set; }

    public virtual ICollection<PlayerGameAnswer> PlayerGameAnswers { get; set; } = new List<PlayerGameAnswer>();

    public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; } = new List<QuestionAnswer>();
}