// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EscapeRoomAPI.Entities;

public partial class QuestionAnswer
{
    public int Id { get; set; }

    public string QuestionAnswerId { get; set; }

    public string Answer { get; set; }

    public string QuestionId { get; set; }

    public bool IsTrue { get; set; }

    public virtual ICollection<PlayerGameAnswer> PlayerGameAnswers { get; set; } = new List<PlayerGameAnswer>();

    public virtual Question Question { get; set; }
}